name: CI

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: registry.access.redhat.com/ubi9

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          dnf install -y python-jsonschema
          curl -sO https://github.com/spdx/spdx-spec/raw/development/v2.3/schemas/spdx-schema.json
          for example in $GITHUB_WORKSPACE/examples/rpm/*.json; do
            jsonschema spdx-schema.json -i $example
          done
